import { requireMcpCheck } from './lib/precheck.js';
import fs from 'fs-extra';
import path from 'path';
import mustache from 'mustache';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { callLLM } from './llm-client.js';

function parseArgs() {
  const args = process.argv.slice(2);
  const out = { modes: [], dryRun: true, apply: false, stagingDir: null };
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if ((a === '--modes' || a === '-M') && args[i+1]) {
      out.modes = args[i+1].split(',').map(s => s.trim()); i++; }
    else if (a === '--mode' && args[i+1]) { out.modes.push(args[i+1]); i++; }
    else if (a === '--mcp-url' && args[i+1]) { out.mcpUrl = args[i+1]; i++; }
    else if ((a === '--staging-dir' || a === '--staging') && args[i+1]) { out.stagingDir = args[i+1]; i++; }
    else if (a === '--apply') { out.apply = true; out.dryRun = false; }
    else if (a === '--dry-run') { out.dryRun = true; out.apply = false; }
  }
  return out;
}

async function main() {
  const args = parseArgs();
  if (!args.modes || args.modes.length === 0) {
    console.error('No modes provided. Use --modes file1.json,file2.json or --mode <file>');
    process.exit(2);
  }

  for (const m of args.modes) {
    const modePath = path.resolve(process.cwd(), m);
    if (!await fs.pathExists(modePath)) {
      console.error('Mode file not found:', modePath);
      process.exit(2);
    }
    console.log('Pre-checking mode:', modePath);
    const res = await requireMcpCheck(modePath, { mcpUrl: args.mcpUrl });
    if (!res.ok) {
      if (res.reason === 'no_mcp_url_configured') {
        console.error('Mode requires MCP but no MCP URL configured. Set MCP_SERVER_URL or pass --mcp-url.');
      } else {
        console.error('MCP pre-check failed for mode:', modePath, 'reason:', res.reason, 'probeUrl:', res.probeUrl);
      }
      console.error('Aborting pipeline. Fix MCP availability and retry.');
      process.exit(2);
    }
    console.log('Pre-check passed for mode:', modePath);
  }

  console.log('All pre-checks passed. Ready to run modes.');
  // Load and execute each mode sequentially
  const ajv = new Ajv({ allErrors: true, strict: false });
  addFormats(ajv);

  let runtime = {};
  for (const m of args.modes) {
    const modePath = path.resolve(process.cwd(), m);
    const raw = await fs.readFile(modePath, 'utf8');
    const mode = JSON.parse(raw);

    // Render user messages with runtime
    const renderedMessages = (mode.messages || []).map(msg => {
      return { role: msg.role, content: mustache.render(msg.content || '', { runtime }) };
    });

    // Call LLM (mocked by default)
    let responseText;
    try {
      responseText = await callLLM(mode, renderedMessages);
    } catch (e) {
      console.error('LLM call failed for mode', modePath, e.message || e);
      process.exit(2);
    }

    // Try parse JSON
    let parsed;
    try { parsed = JSON.parse(responseText); }
    catch (e) {
      // try to extract JSON object from text
      const match = responseText.match(/\{[\s\S]*\}/);
      if (match) parsed = JSON.parse(match[0]);
      else { console.error('LLM did not return valid JSON for mode', modePath); process.exit(2); }
    }

    // Validate against schema if present
    if (mode.output_schema) {
      const validate = ajv.compile(mode.output_schema);
      const valid = validate(parsed);
      if (!valid) {
        console.error('Validation failed for mode', modePath, ajv.errorsText(validate.errors, { separator: '\n' }));
        process.exit(2);
      }
    }

    // Persist runtime
    runtime[mode.meta?.id || path.basename(modePath, '.json')] = parsed;

    // Prefer structured files output (files array). Fall back to files_created (legacy).
    const files = Array.isArray(parsed.files) ? parsed.files : null;
    const legacy = Array.isArray(parsed.files_created) ? parsed.files_created : null;

    // Prepare list of file objects to write (path, content, encoding)
    const fileObjects = [];
    if (files) {
      for (const f of files) {
        fileObjects.push({ path: f.path, content: f.content, encoding: f.encoding || 'utf8', mode: f.mode });
      }
    } else if (legacy) {
      // For legacy, create simple JSON dump files at the requested paths
      for (const f of legacy) {
        fileObjects.push({ path: f, content: `# Generated by mode ${mode.meta?.id || ''}\n\n` + JSON.stringify(parsed, null, 2), encoding: 'utf8' });
      }
    }

    // Dry-run: show what would be written
    if (!fileObjects.length) {
      console.log('No files to write for mode', modePath);
      continue;
    }

    console.log('\n=== Mode output files preview ===');
    for (const fo of fileObjects) {
      // sanitize path: disallow absolute
      if (path.isAbsolute(fo.path)) {
        console.error('Refusing to write unsafe absolute path:', fo.path);
        process.exit(2);
      }
      // compute target inside stagingDir if provided, else repo root
      const baseDir = args.stagingDir ? path.resolve(process.cwd(), args.stagingDir) : path.resolve(process.cwd(), '..', '..');
      const target = path.resolve(baseDir, fo.path);
      // Prevent path traversal outside baseDir
      const rel = path.relative(baseDir, target);
      if (rel.startsWith('..') || path.isAbsolute(rel)) {
        console.error('Refusing to write unsafe path (outside stagingDir):', fo.path);
        process.exit(2);
      }
      console.log(`${fo.encoding === 'base64' ? '[binary]' : ''} -> ${target}`);
      if (!args.apply) {
        // show small preview for text files
        if (fo.encoding === 'utf8') {
          const preview = fo.content.split('\n').slice(0, 20).join('\n');
          console.log('--- preview ---');
          console.log(preview);
          if (fo.content.split('\n').length > 20) console.log('... (truncated)');
        } else {
          console.log('(binary content omitted)');
        }
      }
    }

    if (args.apply) {
      for (const fo of fileObjects) {
        const baseDir = args.stagingDir ? path.resolve(process.cwd(), args.stagingDir) : path.resolve(process.cwd(), '..', '..');
        const target = path.resolve(baseDir, fo.path);
        await fs.ensureDir(path.dirname(target));
        if (fo.encoding === 'base64') {
          const buf = Buffer.from(fo.content, 'base64');
          await fs.writeFile(target, buf);
        } else {
          await fs.writeFile(target, fo.content, 'utf8');
        }
        if (fo.mode) {
          try { await fs.chmod(target, fo.mode); } catch (e) { /* ignore chmod errors on Windows */ }
        }
        console.log('Wrote file:', target);
      }
    } else {
      console.log('\nDry run mode — no files were written. To apply files, re-run with --apply');
    }
  }

  console.log('Pipeline completed successfully.');
  process.exit(0);
}

main().catch(err => { console.error(err); process.exit(2); });
