name: Publish to npm and MCP Registry

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Configure npm for retry
        run: |
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set fetch-retries 5
      
      - name: Install dependencies with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 30
          command: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Publish to npm
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 30
          command: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update server.json version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          jq --arg v "$VERSION" '.version = $v | .packages[0].version = $v' server.json > tmp && mv tmp server.json

      - name: Install MCP Publisher
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 15
          command: |
            curl -L "https://github.com/modelcontextprotocol/registry/releases/download/latest/mcp-publisher_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher
            chmod +x mcp-publisher

      - name: Login to MCP Registry
        id: mcp-login
        continue-on-error: true
        run: ./mcp-publisher login github-oidc

      - name: Publish to MCP Registry
        id: mcp-publish
        if: steps.mcp-login.outcome == 'success'
        continue-on-error: true
        run: ./mcp-publisher publish
        
      - name: MCP Registry publish status
        run: |
          if [[ "${{ steps.mcp-login.outcome }}" != "success" ]]; then
            echo "⚠️  MCP Registry login failed - check OIDC configuration"
          elif [[ "${{ steps.mcp-publish.outcome }}" != "success" ]]; then
            echo "⚠️  MCP Registry publish failed - manual publish may be needed"
          else
            echo "✅ Successfully published to MCP Registry"
          fi
